# Generated by Django 6.0.3 on 2026-03-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_celiac',
            field=models.BooleanField(default=False, verbose_name='Celiac / Gluten Intolerance'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_lactose_intolerance',
            field=models.BooleanField(default=False, verbose_name='Lactose Intolerance'),
        ),
    ]
