# Generated by Django 6.0.3 on 2026-03-14 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_userprofile_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fasting_mode',
            field=models.CharField(choices=[('none', 'No Fasting'), ('16_8', 'Intermittent 16:8'), ('5_2', 'Intermittent 5:2'), ('omad', 'One Meal a Day (OMAD)')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='region_preference',
            field=models.CharField(choices=[('north', 'North Indian'), ('south', 'South Indian'), ('bengali', 'Bengali'), ('gujarati', 'Gujarati'), ('maharashtrian', 'Maharashtrian')], default='north', max_length=20),
        ),
        migrations.CreateModel(
            name='WeightHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('bmi', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
    ]
